apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-api-deply
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: fast-api-1
  template:
    metadata:
      labels:
        app: fast-api-1
    spec:
      containers:
      - name: fast-api-1
        image: linxitcld/linxits_fastapi:movie-service.1
        resources:
          limits:
             memory: "265Mi"
             cpu: "500m"
        ports:
        - containerPort: 8000
